### ISSUE TITLE
r,g,b,a issue

### ISSUE THREAD

**Issue by ImTiredRat** [tomlum/simpleScale#2]
found issue in code for simpleScale.unSet(r,g,b,a)
original code had an issue where it had `simpleScale.unSet(coloR,g,b,a)` and it set the r,g,b,a to love.graphics.getColor() before testing if r was nil meaning that it would always set the letterbox to {0,0,0}
I changed it to this: 
![fix](https://user-images.githubusercontent.com/34012814/36705303-67bd86d6-1b32-11e8-8923-b0e56299ee70.png)
thanks for updating it btw!

**Comment by tomlum** [comment]
Great catch, thanks for the spot!  A fix has been pushed.

I think your fix has a slightly different behavior where the letter boxes are the last set color if there's no given input, whereas now the fix is to default to black with no inputs.
